### ISSUE TITLE
Tilføj effektcirkler

### ISSUE THREAD

**Issue by BoomerNik** [aartools/effektkompas#24]

**Comment by aartools** [comment]
Ide: Polære koordinater

Knap "Tilføj cirkel" -> Tilføjer 2 sliders

Slider "Vinkel"
Slider "Afstand til centrum"

**Comment by aartools** [comment]
Ide: Polære koordinater **_Mathias Edition_**

Skrives i tekst-feltet:

@cirkel v45 r66 Dette er en effektcirkel.
@cirkel v138 r78 Dette er også en effektcirkel \\ Men med 2 linjer.
