### ISSUE TITLE
Vend tekst på nedre halvdel af cirkelen

### ISSUE THREAD

**Issue by StephAARTnie** [aartools/effektkompas#3]
Så man kan læse det, ikå

**Comment by aartools** [comment]
Er det ikke allerede gjort?

**Comment by StephAARTnie** [comment]
Jo, det er det da! Jeg har åbenbart ikke set den nyeste version. Den kan vidst lukke sog slukkes

**Comment by StephAARTnie** [comment]
![image](https://user-images.githubusercontent.com/86344627/123055211-efeace80-d405-11eb-90ad-b3a481ab369c.png)
![image](https://user-images.githubusercontent.com/86344627/123055329-0f81f700-d406-11eb-8628-a8f49a548a9e.png)


Inden du lukker den så er der noget med linjeskiftet, hvor man skal skrive det omvendt i den nedrste halvdel af cirkelen
